name: incode_demo
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: "3.5.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  # Incode
  onboarding_flutter_wrapper:
    git:
      url: git@github.com:Incode-Technologies-Example-Repos/IncdOnboardingFlutter.git
      ref: release/4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
